### ISSUE TITLE
django runserver does not find module

### ISSUE THREAD

**Issue by mtaziz** [Gerapy/Gerapy#1]
Hi, 
I was trying to run django server but I am receiving the below error. 
Could you please have look into the following message. 
Should I use ```gerapy runserver```? 
Could you tell me how to execute the above command? 

Thanks ahead for your help in this regard. 

```
→ ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 27, in <module>
    manage()
  File "./manage.py", line 23, in manage
    execute_from_command_line(sys.argv)
  File "/home/mtaziz/.virtualenvs/onescience_dist_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/mtaziz/.virtualenvs/onescience_dist_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/mtaziz/.virtualenvs/onescience_dist_env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/mtaziz/.virtualenvs/onescience_dist_env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mtaziz/.virtualenvs/onescience_dist_env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named gerapy.server.server.settings

```

**Comment by Germey** [comment]
Just run:

```
pip3 install gerapy
```

Thanks for your issue, I'v replied to you in the email before.
