### ISSUE TITLE
 gerapy runserver命令启动是出错

### ISSUE THREAD

**Issue by limbo-envoy** [Gerapy/Gerapy#112]
![image](https://user-images.githubusercontent.com/30359746/65222151-1113e200-daf1-11e9-9b2e-e8261efd5e89.png)
当我运行 gerapy runserve报了这个错误SystemError: <built-in function getattr> returned a result with an error set。我用的是windows系统，执行环境是自己创建的一个虚拟环境中，gerapy初始化成功，并且gerapy migrate迁移也没问题，就是启动报错，应该不会就用不了吧？现在我启动不了，请帮忙看下怎么解决

**Comment by limbo-envoy** [comment]
我现在启动还是报错，我看报错信息好像是django引发的一个错误，我的django是用的2.2.5版本的
完整报错信息我都贴上来了，不知道有没有帮助
λ gerapy runserver                                                                                             
Watching for file changes with StatReloader                                                                    
Performing system checks...                                                                                    
                                                                                                               
AttributeError: cffi library '_constant_time' has no function, constant or global variable named '__spec__'    
                                                                                                               
The above exception was the direct cause of the following exception:                                           
                                                                                                               
Traceback (most recent call last):                                                                             
  File "c:\users\gfkf05\appdata\local\programs\python\python36\Lib\runpy.py", line 193, in _run_module_as_main 
    "__main__", mod_spec)                                                                                      
  File "c:\users\gfkf05\appdata\local\programs\python\python36\Lib\runpy.py", line 85, in _run_code            
    exec(code, run_globals)                                                                                    
  File "E:\virtualenv\my_spider\Scripts\gerapy.exe\__main__.py", line 9, in <module>                           
  File "e:\virtualenv\my_spider\lib\site-packages\gerapy\cmd\__init__.py", line 26, in cmd                     
    server()                                                                                                   
  File "e:\virtualenv\my_spider\lib\site-packages\gerapy\cmd\server.py", line 6, in server                     
    manage()                                                                                                   
  File "e:\virtualenv\my_spider\lib\site-packages\gerapy\server\manage.py", line 24, in manage                 
    execute_from_command_line(sys.argv)                                                                        
  File "e:\virtualenv\my_spider\lib\site-packages\django\core\management\__init__.py", line 381, in execute_fro
m_command_line                                                                                                 
    utility.execute()                                                                                          
  File "e:\virtualenv\my_spider\lib\site-packages\django\core\management\__init__.py", line 375, in execute    
    self.fetch_command(subcommand).run_from_argv(self.argv)                                                    
  File "e:\virtualenv\my_spider\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv  
    self.execute(*args, **cmd_options)                                                                         
  File "e:\virtualenv\my_spider\lib\site-packages\django\core\management\commands\runserver.py", line 60, in ex
ecute                                                                                                          
    super().execute(*args, **options)                                                                          
  File "e:\virtualenv\my_spider\lib\site-packages\django\core\management\base.py", line 364, in execute        
    output = self.handle(*args, **options)                                                                     
  File "e:\virtualenv\my_spider\lib\site-packages\django\core\management\commands\runserver.py", line 95, in ha
ndle                                                                                                           
    self.run(**options)                                                                                        
  File "e:\virtualenv\my_spider\lib\site-packages\django\core\management\commands\runserver.py", line 102, in r
un                                                                                                             
    autoreload.run_with_reloader(self.inner_run, **options)                                                    
  File "e:\virtualenv\my_spider\lib\site-packages\django\utils\autoreload.py", line 598, in run_with_reloader  
    start_django(reloader, main_func, *args, **kwargs)                                                         
  File "e:\virtualenv\my_spider\lib\site-packages\django\utils\autoreload.py", line 583, in start_django       
    reloader.run(django_main_thread)                                                                           
  File "e:\virtualenv\my_spider\lib\site-packages\django\utils\autoreload.py", line 301, in run                
    self.run_loop()                                                                                            
  File "e:\virtualenv\my_spider\lib\site-packages\django\utils\autoreload.py", line 307, in run_loop           
    next(ticker)                                                                                               
  File "e:\virtualenv\my_spider\lib\site-packages\django\utils\autoreload.py", line 347, in tick               
    for filepath, mtime in self.snapshot_files():                                                              
  File "e:\virtualenv\my_spider\lib\site-packages\django\utils\autoreload.py", line 363, in snapshot_files     
    for file in self.watched_files():                                                                          
  File "e:\virtualenv\my_spider\lib\site-packages\django\utils\autoreload.py", line 262, in watched_files      
    yield from iter_all_python_module_files()                                                                  
  File "e:\virtualenv\my_spider\lib\site-packages\django\utils\autoreload.py", line 103, in iter_all_python_mod
ule_files                                                                                                      
    return iter_modules_and_files(modules, frozenset(_error_files))                                            
  File "e:\virtualenv\my_spider\lib\site-packages\django\utils\autoreload.py", line 124, in iter_modules_and_fi
les                                                                                                            
    if getattr(module, '__spec__', None) is None:                                                              
SystemError: <built-in function getattr> returned a result with an error set  
蛮想用你们这个部署的，但现在第一步都没迈出去<笑哭>

**Comment by limbo-envoy** [comment]
哦， 是django版本的问题，我降低了django版本，从2.2.5降到了2.1.8，现在可以启动了

**Comment by Germey** [comment]
目前还没适配高的版本，后期会继续适配
