### ISSUE TITLE
gerapy.spider文件是有问题吗？

### ISSUE THREAD

**Issue by hellokuls** [Gerapy/Gerapy#135]
看了大佬发的视频，我按照同样的步骤配置了相同网站的爬虫，但是爬虫每次都爬取不到信息。后面我将生成的scrapy项目中的爬虫文件里的
`from gerapy.spiders import CrawlSpider`
改成了
`from scrapy.spiders import CrawlSpider`

才能够正常爬取，不知道原因是啥？

**Comment by Germey** [comment]
CrawlSpider 里面是对 Scrapy 的 CrawlSpider 进行了改写，变动还不少，增加了一些参数，这些可配置化功能不太敢保证一定稳定，如果方便的话，看能否将生成的 Scrapy 项目上传一下，我来排查下是什么问题。

**Comment by hellokuls** [comment]
麻烦大佬了！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"崔庆才丨静觅"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月30日(星期四) 上午10:38
收件人:&nbsp;"Gerapy/Gerapy"<Gerapy@noreply.github.com&gt;;
抄送:&nbsp;"1839938674"<1839938674@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Gerapy/Gerapy] gerapy.spider文件是有问题吗？ (#135)




CrawlSpider 里面是对 Scrapy 的 CrawlSpider 进行了改写，变动还不少，增加了一些参数，这些可配置化功能不太敢保证一定稳定，如果方便的话，看能否将生成的 Scrapy 项目上传一下，我来排查下是什么问题。

**Comment by Germey** [comment]
好像没收到，可以转发给 cqc@cuiqingcai.com 吗

**Comment by hellokuls** [comment]
不知道大佬收到文件没？麻烦大佬指点一下

**Comment by Germey** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    不好意思哈，我这几天在家办公有点忙，忘记这件事情了，我明天看一下。
    
        
            
        
    
    
          
        
            
    
        font{
            line-height: 1.6;
        }
    
崔庆才   微软中国Email: cqc@cuiqingcai.com    Wechat: CQCcqc北京市海淀区丹棱街5号微软研发大厦2号楼

        
    
     
    

    在2020年02月9日 19:32，hellokuls<notifications@github.com> 写道： 


不知道大佬收到文件没？麻烦大佬指点一下

**Comment by Germey** [comment]
不好意思啊，这几天在家办公比较忙，忘记这件事了，我明天看一下，实在抱歉。

**Comment by Germey** [comment]
测试了下，的确发现是我 Gerapy 的 Rule 编写的问题，估计你之前的错误是：

```python
  File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/scrapy/spiders/crawl.py", line 112, in _parse_response
    for request_or_item in self._requests_to_follow(response):
  File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/gerapy/spiders/crawl.py", line 151, in _requests_to_follow
    r = self._generate_request(index, rule, link, response)
  File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/gerapy/spiders/crawl.py", line 108, in _generate_request
    url = furl(link.url).add(rule.params).url if rule.params else link.url
AttributeError: 'Rule' object has no attribute 'params'
```

我进行了一些修复，放在了 master，之前的错误没有了，但现在测着还是有点小问题：

```python
2020-02-11 03:01:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://tech.china.com/article/20190520/20190520293312.html> (referer: None)
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/scrapy/spiders/crawl.py", line 101, in _response_downloaded
    rule = self._rules[response.meta['rule']]
KeyError: 'rule'
```

我会再修复一下试试，尽快发布一个较为稳定的版本，发布之后回复您。

期间您可以先临时将 gerapy 改成 scrapy 来使用。

**Comment by hellokuls** [comment]
好的，非常感谢！





------------------ 原始邮件 ------------------
发件人: 崔庆才丨静觅 <notifications@github.com&gt;
发送时间: 2020年2月11日 03:15
收件人: Gerapy/Gerapy <Gerapy@noreply.github.com&gt;
抄送: hellokuls <1839938674@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Gerapy/Gerapy] gerapy.spider文件是有问题吗？ (#135)




测试了下，的确发现是我 Gerapy 的 Rule 编写的问题，估计你之前的错误是：
   File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr&gt;     return (r for r in result or () if _filter(r))   File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable     for r in iterable:   File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr&gt;     return (r for r in result or () if _filter(r))   File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/scrapy/spiders/crawl.py", line 112, in _parse_response     for request_or_item in self._requests_to_follow(response):   File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/gerapy/spiders/crawl.py", line 151, in _requests_to_follow     r = self._generate_request(index, rule, link, response)   File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/gerapy/spiders/crawl.py", line 108, in _generate_request     url = furl(link.url).add(rule.params).url if rule.params else link.url AttributeError: 'Rule' object has no attribute 'params'
 
我进行了一些修复，放在了 master，之前的错误没有了，但现在测着还是有点小问题：
 2020-02-11 03:01:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://tech.china.com/article/20190520/20190520293312.html&gt; (referer: None) Traceback (most recent call last):   File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks     current.result = callback(current.result, *args, **kw)   File "/usr/local/Caskroom/miniconda/base/envs/gerapy/lib/python3.6/site-packages/scrapy/spiders/crawl.py", line 101, in _response_downloaded     rule = self._rules[response.meta['rule']] KeyError: 'rule'
 
我会再修复一下试试，尽快发布一个较为稳定的版本，发布之后回复您。
 
期间您可以先临时将 gerapy 改成 scrapy 来使用。

**Comment by hellokuls** [comment]
![image](https://user-images.githubusercontent.com/42165104/75676889-2c506380-5cc5-11ea-9687-8bf07343c131.png)
发现了个新的错误，经过简单的排查，发现是下面红框这句话报错
![image](https://user-images.githubusercontent.com/42165104/75676858-1773d000-5cc5-11ea-9449-0f2962d2f1d5.png)

mysql的中间件出问题，我用scrapy运行爬虫，无法保存到数据库。

我之前说的gerapy.spider文件，麻烦大佬尽快修复一下，感谢！

**Comment by Germey** [comment]
`from gerapy.spiders import CrawlSpider` 是 configurable 模块提供的可配置爬虫基类；改成 scrapy 的之后配置就失效了，所以爬不到内容其实是规则/配置本身的问题，与导入无关。configurable 模块为实验性，建议直接写 Scrapy 爬虫。已关闭。
