### ISSUE TITLE
Unable to create spider

### ISSUE THREAD

**Issue by vyombriq** [Gerapy/Gerapy#136]
I am not able to create spider

**To Reproduce**
1. Created a new project
2. added starting URL and Domain
3. clicked on run 

**Traceback**
 Traceback (most recent call last):
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\vyomb\AppData\Local\Programs\Python\Python38-32\Scripts\gerapy.exe\__main__.py", line 9, in <module>
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\site-packages\gerapy\cmd\__init__.py", line 140, in cmd
    parse(args)
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\site-packages\gerapy\cmd\parse.py", line 14, in parse
    results = get_start_requests(project_path, args.spider)
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\site-packages\gerapy\server\core\parser.py", line 197, in get_start_requests
    runner = CrawlerRunner(settings=settings)
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\site-packages\scrapy\crawler.py", line 145, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\site-packages\scrapy\crawler.py", line 347, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\site-packages\scrapy\spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\site-packages\scrapy\spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\site-packages\scrapy\spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\site-packages\scrapy\utils\misc.py", line 73, in walk_modules
    submod = import_module(fullpath)
  File "c:\users\vyomb\appdata\local\programs\python\python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Gerapy\gerapy\projects\spidy\spidy\spiders\test.py", line 23
    def (self, response):
        ^
SyntaxError: invalid syntax

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]  Windows 10
 - Browser [e.g. Chrome 67]  Chrome 67

**Screenshots**
<img width="612" alt="Capture" src="https://user-images.githubusercontent.com/59594793/73652812-bea51d80-46ad-11ea-8eb9-a360944f70a9.PNG">

 - Python Version [e.g. 3.6.2] 3.8

**Comment by vyombriq** [comment]
can you show a video demo of creating a spider for one project @Germey

**Comment by Germey** [comment]
The function of generating code is not perfect, I am testing it, so some problems may occur, so this function has not been documented. In recent days, I will quickly complete this function, and then release a new version and write documentation. Thanks for your support!

**Comment by vyombriq** [comment]
Hey,

Thanks for the quick reply. I just wanted to confirm are you having
functionality of visual scrapping ie user should select from the webpage
whatever he needs spider to scrape.
I was going through your code as it was using scrapy-splash , so i was in
the impression that it would be having visual scrapping.

Please can you confirm that does gerapy has visual scrapping thing
implemented or you need to develop it in future.

Regards
Vyom Saxena
Full Stack Engineer
*Briq *

**Comment by Germey** [comment]
Yes, I have implemented the configuration of the visual crawler. According to the configuration, the code of the Scrapy framework can be automatically generated. In addition, I have also integrated Scrapy-Splash and Pyppeteer to implement dynamic content rendering, and I can also integrate Scrapy-Redis to implement distributed Crawl, and you can also configure storage functions such as MongoDB, MySQL, etc. These codes can be automatically generated through configuration.

In addition, I also imitated PySpider to develop a set of Scrapy visual debugging tools, rewritten the logic of CrawlSpider and CrawlSpider / Rule Class, and perfected some content to enable debugging.

At present, the above functions have a preliminary version, now in the master branch, if you are interested, you can view the source code. But the function is not very stable now, so it has been in the testing stage, and the official version has not been released yet, so the related functions have not been written in the documentation. I will develop and release a stable version as soon as possible. Thank you.

**Comment by vyombriq** [comment]
Hey ,
Thanks for the quick reply.

Congratulations for the great job you are doing to build Gerapy.

I was looking into the code you did a great job on adding lots of
functionality ,can you just add a quick demo(gif) to just show the visual
scrapping in Gerapy. It will help me to get how the flow works.

Can you please send a demo(gif) with the functionality of visual scrapping
atleast.

Thanks

**Comment by Germey** [comment]
Sure, I have some work to do in my company, after I finished them. I'll prepare some demos for you, during the time, If something like bug occurs, I'll try to fix it. So It may take some time more, I'll do it as soon as possible. Thanks.

**Comment by vyombriq** [comment]
Hey Gerapy/Gerapy,

I just wanted to know if you got time to prepare the demos.Actually I am
not able to create a spider for any domain, it's giving me error ,and I am
not able to fix the issue.
Can you please help me by sending a demo with a process of visual scrapping
data from any website.

Thanks and Regards

**Comment by vyombriq** [comment]
Hey Gerapy, 

I was trying to create a spider but was unable to do so there was some syntax error in quotespider.py file.

Please refer to this [https://screencast-o-matic.com/watch/cYnFXgwgbb](https://screencast-o-matic.com/watch/cYnFXgwgbb)

**Comment by vyombriq** [comment]
i tried adding code for parsing from my own but still its giving me error
![image](https://user-images.githubusercontent.com/59594793/74740992-0026f280-5282-11ea-8be5-80e4311d1383.png)

My quotespider.py file 


```
from scrapy.linkextractors import LinkExtractor
from gerapy.spiders import CrawlSpider
from gerapy.spiders import Rule
from scrapy.loader import ItemLoader
# from ..items import *
from scrapy.loader.processors import *


class QuotespiderSpider(CrawlSpider):
    name = 'quotespider'
    allowed_domains = ['quotes.toscrape', ]
    custom_settings = {

        "DOWNLOADER_MIDDLEWARES": {"gerapy.downloadermiddlewares.pyppeteer.PyppeteerMiddleware": 601,
                                   "scrapy_splash.SplashCookiesMiddleware": 723, "scrapy_splash.SplashMiddleware": 725,
                                   "scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware": 810},
        "SPIDER_MIDDLEWARES": {"scrapy_splash.SplashDeduplicateArgsMiddleware": 100},
        "ITEM_PIPELINES": {},
    }
    start_urls = ['http://quotes.toscrape.com/', ]

    def parse(self, response):
        for quote1 in response.css("div.quote"):
            yield {
                'text': quote1.css("span.text::text").extract_first().replace("\u201c", "").replace("\u201d", ""),
                'author': quote1.css("small.author::text").extract_first(),
                'tags': quote1.css("div.tags a.tag::text").extract(),
            }
        next_page = response.css("li.next a::attr(href)").extract_first()
        if next_page:
            yield response.follow(next_page, callback=self.parse)


```

**Comment by vyombriq** [comment]
Hi Germey,
I was waiting for the demos, can you please send a basic demo showing
visual scrapping , so that i can start implementing on top of that.

Thanks
Regards
Vyom Saxena
Full Stack Engineer
*Briq *

**Comment by Germey** [comment]
I am very sorry that there are some other things in the past few days that are processing your time. I am sorry to have kept you waiting so long.

According to your running problem, it may be a coding problem, not a logical problem of Gerapy itself. But it is true that Gerapy will also have some logic problems. I am trying to fix it. I will try my best to fix him as soon as possible. I will tell you when the test is stable.

Prior to this, you can directly modify the Gerapy related code in the site-package to troubleshoot the bugs you encountered, and you can also refer to this document https://docs.gerapy.com/en/latest/contributing.html to build and develop Environment, you can debug and repair Gerapy.

Thank you very much, I still have a lot of tasks that I have not completed, and I will help you solve them as soon as possible after I complete them.

**Comment by robinsonkwame** [comment]
@vyombriq @Germey the open source [changedetection.io](https://github.com/dgtlmoon/changedetection.io) has visual scraping (using [Playwright](https://github.com/dgtlmoon/changedetection.io/wiki/Playwright-content-fetcher)). @Germey you may want to port its Visual Selector tool to this library to save time.

**Comment by Germey** [comment]
The traceback ends in `spiders/test.py, line 23: def (self, response): SyntaxError: invalid syntax` — your spider file has a Python syntax error (a `def` with no name). Fix the spider source and it will load. This is a user code error, not a Gerapy bug. Closing.
