### ISSUE TITLE
安装一直出现错误，网上貌似没有找到答案

### ISSUE THREAD

**Issue by levia-than** [Gerapy/Gerapy#141]
在安装的时候，出现了如下的错误提示：
ERROR: Command errored out with exit status 1:
     command: 'c:\users\lion messi\appdata\local\programs\python\python35\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LIONME~1\\AppData\\Local\\Temp\\pip-install-popc51m4\\pyppeteer\\setup.py'"'"'; __file__='"'"'C:\\Users\\LIONME~1\\AppData\\Local\\Temp\\pip-install-popc51m4\\pyppeteer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\LIONME~1\AppData\Local\Temp\pip-install-popc51m4\pyppeteer\
    Complete output (32 lines):
    Requirement already satisfied: py-backwards in c:\users\lion messi\appdata\local\programs\python\python35\lib\site-packages (0.7)
    Requirement already satisfied: colorama in c:\users\lion messi\appdata\roaming\python\python35\site-packages (from py-backwards) (0.4.3)
    Requirement already satisfied: typed-ast in c:\users\lion messi\appdata\roaming\python\python35\site-packages (from py-backwards) (1.4.1)
    Requirement already satisfied: autopep8 in c:\users\lion messi\appdata\local\programs\python\python35\lib\site-packages (from py-backwards) (1.5)
    Requirement already satisfied: py-backwards-astunparse in c:\users\lion messi\appdata\local\programs\python\python35\lib\site-packages (from py-backwards) (1.5.0.post3)
    Requirement already satisfied: pycodestyle>=2.5.0 in c:\users\lion messi\appdata\local\programs\python\python35\lib\site-packages (from autopep8->py-backwards) (2.5.0)
    Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\lion messi\appdata\local\programs\python\python35\lib\site-packages (from py-backwards-astunparse->py-backwards) (0.34.2)
    Requirement already satisfied: six<2.0,>=1.6.1 in c:\users\lion messi\appdata\roaming\python\python35\site-packages (from py-backwards-astunparse->py-backwards) (1.14.0)
    Traceback (most recent call last):
      File "C:\Users\LIONME~1\AppData\Local\Temp\pip-install-popc51m4\pyppeteer\setup.py", line 19, in <module>
        from py_backwards.compiler import compile_files
      File "c:\users\lion messi\appdata\local\programs\python\python35\lib\site-packages\py_backwards\compiler.py", line 8, in <module>
        from .files import get_input_output_paths, InputOutput
      File "c:\users\lion messi\appdata\local\programs\python\python35\lib\site-packages\py_backwards\files.py", line 9, in <module>
        from .exceptions import InvalidInputOutput, InputDoesntExists
      File "c:\users\lion messi\appdata\local\programs\python\python35\lib\site-packages\py_backwards\exceptions.py", line 1, in <module>
        from typing import Type, TYPE_CHECKING
    ImportError: cannot import name 'Type'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LIONME~1\AppData\Local\Temp\pip-install-popc51m4\pyppeteer\setup.py", line 25, in <module>
        from py_backwards.compiler import compile_files
      File "c:\users\lion messi\appdata\local\programs\python\python35\lib\site-packages\py_backwards\compiler.py", line 8, in <module>
        from .files import get_input_output_paths, InputOutput
      File "c:\users\lion messi\appdata\local\programs\python\python35\lib\site-packages\py_backwards\files.py", line 9, in <module>
        from .exceptions import InvalidInputOutput, InputDoesntExists
      File "c:\users\lion messi\appdata\local\programs\python\python35\lib\site-packages\py_backwards\exceptions.py", line 1, in <module>
        from typing import Type, TYPE_CHECKING
    ImportError: cannot import name 'Type'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
本人大一新生一枚，已经在网上找了很久了，都没有找到问题的根源。
系统：win10 pro
还恳请各位大佬出手相助。

**Comment by Germey** [comment]
试一下 Python 3.6 吧，3.5 的 type 不支持。

**Comment by levia-than** [comment]
谢谢大佬相助！！
