### ISSUE TITLE
在任务管理中创建的任务，删除失败且查看状态显示加载失败。

### ISSUE THREAD

**Issue by a2011318824** [Gerapy/Gerapy#209]
**Describe the bug**
我在任务管理中创建了一个爬虫的定时任务，当我去查看状态时，显示加载失败，且该任务无法被删除。
gerapy后台日志报错：
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: djangojobexecution, id, job_state, next_run_time

**Comment by nq2021** [comment]
我也出现这种情况，而且删不掉，任务一直在疯狂定时执行，怎么取消掉？

**Comment by myt2000** [comment]
我也是这种情况，无法加载，删除也删除不掉
[18/Oct/2021 09:43:16] "GET /api/task/1/status HTTP/1.1" 500 21311
Internal Server Error: /api/task/1/status
Traceback (most recent call last):
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "g:\code\gerapy_manage\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "g:\code\gerapy_manage\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "g:\code\gerapy_manage\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "g:\code\gerapy_manage\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "g:\code\gerapy_manage\venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "g:\code\gerapy_manage\venv\lib\site-packages\gerapy\server\core\views.py", line 878, in task_status
    jobs = DjangoJob.objects.filter(name=job_id)
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\db\models\query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\db\models\query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\db\models\sql\query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\db\models\sql\query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\db\models\sql\query.py", line 1190, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\db\models\sql\query.py", line 1049, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "g:\code\gerapy_manage\venv\lib\site-packages\django\db\models\sql\query.py", line 1420, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: djangojobexecution, id, job_state, next_run_time

**Comment by Germey** [comment]
Thanks for your remind, fixed in version 0.9.8
