### ISSUE TITLE
创建定时任务时报创建任务时报AttributeError: 'DjangoJob' object has no attribute 'name'，而且创建成功后不能删除

### ISSUE THREAD

**Issue by YuCoke** [Gerapy/Gerapy#220]
Use "scrapy" to see available commands

INFO - 2021-12-11 13:24:00,216 - process: 10140 - scheduler.py - gerapy.server.core.scheduler - 34 - scheduler - execute job of
 client localhost, project  study_spider, spider  study_spider
Job "execute (trigger: interval[0:01:00], next run at: 2021-12-11 13:25:00 CST)" raised an exception
Traceback (most recent call last):
  File "E:\Program Files\Anaconda3\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "E:\Program Files\Anaconda3\lib\site-packages\gerapy\server\core\scheduler.py", line 38, in execute
    scrapyd.schedule(project_name, spider_name)
  File "E:\Program Files\Anaconda3\lib\site-packages\scrapyd_api\wrapper.py", line 188, in schedule
    json = self.client.post(url, data=data, timeout=self.timeout)
  File "E:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "E:\Program Files\Anaconda3\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "E:\Program Files\Anaconda3\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: Scrapy 2.5.0 - no active project

Unknown command: list

Use "scrapy" to see available commands

**Comment by YuCoke** [comment]
创建任务时报AttributeError: 'DjangoJob' object has no attribute 'name'是什么原因

**Comment by Germey** [comment]
Fixed in 0.9.8, please try:

```
pip3 install -U gerapy
```
