### ISSUE TITLE
通过克隆的方法部署项目，可以运行起来，但是登录不了

### ISSUE THREAD

**Issue by kesyupeng** [Gerapy/Gerapy#233]
**描述错误**
通过克隆的方法部署项目，可以运行，但是登录不了

**重现**
重现行为的步骤:
1. 通过 git clone 克隆仓库到本地
2. 安装好 requirements.txt 所需库，在 Pycharm 里面配置好 `*\Gerapy\gerapy\cmd\__init__.py `运行配置
3. 启动 scrapyd，运行 `*\Gerapy\gerapy\cmd\__init__.py `文件，在 gerapy/client 文件夹下 通过 `npm run serve` 命令启动前端
4. 控制台报错

**Traceback**
将控制台中显示的 traceback 复制到此处：
```python
E:\PycharmProjects\Gerapy\venv\Scripts\python.exe E:/PycharmProjects/Gerapy/gerapy/cmd/__init__.py runserver 0.0.0.0:5000
Watching for file changes with StatReloader
Performing system checks...

DEBUG - 2022-04-02 09:53:53,684 - process: 6920 - scheduler.py - gerapy.server.core.scheduler - 91 - scheduler - syncing jobs from tasks configured...
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
--- Logging error ---
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
System check identified no issues (0 silenced).
Traceback (most recent call last):
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: core_task

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\Python39\lib\logging\__init__.py", line 1083, in emit
    msg = self.format(record)
  File "C:\Python\Python39\lib\logging\__init__.py", line 927, in format
    return fmt.format(record)
  File "C:\Python\Python39\lib\logging\__init__.py", line 663, in format
    record.message = record.getMessage()
  File "C:\Python\Python39\lib\logging\__init__.py", line 367, in getMessage
    msg = msg % self.args
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 250, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 256, in __len__
    self._fetch_all()
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: core_task
Call stack:
  File "C:\Python\Python39\lib\threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "C:\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "E:\PycharmProjects\Gerapy\gerapy\server\core\scheduler.py", line 160, in run
    self.sync_jobs(force=True)
  File "E:\PycharmProjects\Gerapy\gerapy\server\core\scheduler.py", line 93, in sync_jobs
    logger.debug('get realtime tasks %s', tasks)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: core_task

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\Python39\lib\logging\__init__.py", line 1083, in emit
    msg = self.format(record)
  File "C:\Python\Python39\lib\logging\__init__.py", line 927, in format
    return fmt.format(record)
  File "C:\Python\Python39\lib\logging\__init__.py", line 663, in format
    record.message = record.getMessage()
  File "C:\Python\Python39\lib\logging\__init__.py", line 367, in getMessage
    msg = msg % self.args
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 250, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 256, in __len__
    self._fetch_all()
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: core_task
Call stack:
  File "C:\Python\Python39\lib\threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "C:\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "E:\PycharmProjects\Gerapy\gerapy\server\core\scheduler.py", line 160, in run
    self.sync_jobs(force=True)
  File "E:\PycharmProjects\Gerapy\gerapy\server\core\scheduler.py", line 93, in sync_jobs
    logger.debug('get realtime tasks %s', tasks)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: core_task

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "E:\PycharmProjects\Gerapy\gerapy\server\core\scheduler.py", line 160, in run
    self.sync_jobs(force=True)
  File "E:\PycharmProjects\Gerapy\gerapy\server\core\scheduler.py", line 94, in sync_jobs
    for task in tasks:
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 274, in __iter__
    self._fetch_all()
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\PycharmProjects\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: core_task
You have 38 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, authtoken, contenttypes, core, django_apscheduler, sessions.
Run 'python manage.py migrate' to apply them.
April 02, 2022 - 09:53:53
Django version 2.2.27, using settings 'gerapy.server.server.settings'
Starting development server at http://0.0.0.0:5000/
Quit the server with CTRL-BREAK.
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
```

**预期行为**
我希望能成功运行项目并登录进去。

**屏幕截图**
[![qIEAsA.png](https://s1.ax1x.com/2022/04/02/qIEAsA.png)](https://imgtu.com/i/qIEAsA)

**环境:**
 - OS: [Windows 10]
 - Browser [Chrome 99.0.4844.84]
 - Python Version [3.9.4]
 - Gerapy Version [未安装]
 -

**附加上下文**
`*\Gerapy\gerapy\dbs`文件夹下并没有数据库文件

**Comment by kesyupeng** [comment]
**补充**
**第二次尝试，更换了 Python 版本**

**重现**
重现行为的步骤:
根据[https://docs.gerapy.com/en/latest/contributing.html](url) 步骤部署。
1. 通过 git clone 克隆仓库到本地
3. 安装好 requirements.txt 所需库
4. 在 Gerapy 目录下执行 `python3 setup.py install` 命令，执行成功后项目结构如下图：
[![qxlcxf.png](https://s1.ax1x.com/2022/04/07/qxlcxf.png)](https://imgtu.com/i/qxlcxf)
5. 在 gerapy/client 目录下打开终端执行`npm install`，等待良久，新增一文件夹 `node_modules`，下载成功。
6. 在 Pycharm 里面配置好 `*\Gerapy\gerapy\cmd\__init__.py` 运行配置，并运行 `*\Gerapy\gerapy\cmd\__init__.py` 文件，文件配置如图：
[![qx1QQf.md.png](https://s1.ax1x.com/2022/04/07/qx1QQf.md.png)](https://imgtu.com/i/qx1QQf)
7. 启动 scrapyd，如下图：
[![qxlOLF.md.png](https://s1.ax1x.com/2022/04/07/qxlOLF.md.png)](https://imgtu.com/i/qxlOLF)
8. 在 `gerapy/client` 文件夹下 通过 `npm run serve` 命令启动前端，如下图：
9. [![qxlRsS.md.png](https://s1.ax1x.com/2022/04/07/qxlRsS.md.png)](https://imgtu.com/i/qxlRsS)
10. 控制台报错

**Traceback**
```python
Watching for file changes with StatReloader
DEBUG - 2022-04-07 00:06:44,435 - process: 12788 - scheduler.py - gerapy.server.core.scheduler - 91 - scheduler - syncing jobs from tasks configured...
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
--- Logging error ---
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
Traceback (most recent call last):
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: core_task

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\Python36\lib\logging\__init__.py", line 994, in emit
    msg = self.format(record)
  File "C:\Python\Python36\lib\logging\__init__.py", line 840, in format
    return fmt.format(record)
  File "C:\Python\Python36\lib\logging\__init__.py", line 577, in format
    record.message = record.getMessage()
  File "C:\Python\Python36\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 250, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 274, in __iter__
    self._fetch_all()
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: core_task
Call stack:
  File "C:\Python\Python36\lib\threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "C:\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "E:\git\Gerapy\gerapy\server\core\scheduler.py", line 160, in run
    self.sync_jobs(force=True)
  File "E:\git\Gerapy\gerapy\server\core\scheduler.py", line 93, in sync_jobs
    logger.debug('get realtime tasks %s', tasks)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: core_task

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\Python36\lib\logging\__init__.py", line 994, in emit
    msg = self.format(record)
  File "C:\Python\Python36\lib\logging\__init__.py", line 840, in format
    return fmt.format(record)
  File "C:\Python\Python36\lib\logging\__init__.py", line 577, in format
    record.message = record.getMessage()
  File "C:\Python\Python36\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 250, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 274, in __iter__
    self._fetch_all()
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: core_task
Call stack:
  File "C:\Python\Python36\lib\threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "C:\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "E:\git\Gerapy\gerapy\server\core\scheduler.py", line 160, in run
    self.sync_jobs(force=True)
  File "E:\git\Gerapy\gerapy\server\core\scheduler.py", line 93, in sync_jobs
    logger.debug('get realtime tasks %s', tasks)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: core_task

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "E:\git\Gerapy\gerapy\server\core\scheduler.py", line 160, in run
    self.sync_jobs(force=True)
  File "E:\git\Gerapy\gerapy\server\core\scheduler.py", line 94, in sync_jobs
    for task in tasks:
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 274, in __iter__
    self._fetch_all()
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\git\Gerapy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: core_task

System check identified no issues (0 silenced).

You have 38 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, authtoken, contenttypes, core, django_apscheduler, sessions.
Run 'python manage.py migrate' to apply them.
April 07, 2022 - 00:06:44
Django version 2.2.27, using settings 'gerapy.server.server.settings'
Starting development server at http://0.0.0.0:5000/
Quit the server with CTRL-BREAK.
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob
DB error executing '_get_jobs' (no such table: django_apscheduler_djangojob). Retrying with a new DB connection...
Error getting due jobs from job store 'default': no such table: django_apscheduler_djangojob

```

**预期行为**
我希望能成功运行项目并登录进去。

**屏幕截图**
与第一次情况一模一样
[![qIEAsA.png](https://s1.ax1x.com/2022/04/02/qIEAsA.png)](https://imgtu.com/i/qIEAsA)

**环境**
 - OS: [Windows 10]
 - Browser [Chrome 99.0.4844.84]
 - Python Version [3.6.8]
 - Gerapy Version [0.9.10]
 - Development Tools [PyCharm]

**Comment by kesyupeng** [comment]
我用 manage.py 文件运行解决了这个问题
