### ISSUE TITLE
scrapy-redis django.db.utils.OperationalError: database is locked

### ISSUE THREAD

**Issue by chsk4** [Gerapy/Gerapy#237]
**Describe the bug**

**To Reproduce**

**Traceback**
Copy traceback displayed in console to here.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome 67]
 - Python Version [e.g. 3.6.2]
 - Gerapy Version [e.g. 0.8.6]

**Additional context**

**Comment by dimension-data-factory** [comment]
same problem. 
1032 DB error executing 'update_job' (database is locked). Retrying with a new DB connection...                                                                                                                                                                                                                               
1033 Exception in thread APScheduler:
1034 Traceback (most recent call last):
1035   File "/home/anaconda3/envs/spider/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
1036     return self.cursor.execute(sql, params)
1037   File "/home/anaconda3/envs/spider/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
1038     return Database.Cursor.execute(self, query, params)
1039 sqlite3.OperationalError: database is locked
1040 
1041 The above exception was the direct cause of the following exception:
1042 
1043 Traceback (most recent call last):
1044   File "/home/anaconda3/envs/spider/lib/python3.9/site-packages/django_apscheduler/util.py", line 99, in func_wrapper
1045     result = func(*args, **kwargs)

**Comment by Germey** [comment]
Fixed in #324 (merged to `master`).

Raised the SQLite busy `timeout` to 20s (`OPTIONS: {'timeout': ...}`, tunable via `SQLITE_TIMEOUT`) so concurrent writers from the scheduler thread and the web server wait for the lock rather than erroring with *database is locked*. For very write-heavy setups, WAL journal mode or MySQL/PostgreSQL is still the more robust option.
