### ISSUE TITLE
python3.10 任务无法运行和显示

### ISSUE THREAD

**Issue by InfernalAzazel** [Gerapy/Gerapy#239]
**Describe the bug**

**To Reproduce**

**Traceback**
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/desay/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 901, in _create_plugin_instance
    plugin_cls = class_container[alias]
KeyError: 'date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/desay/.local/lib/python3.10/site-packages/gerapy/server/core/scheduler.py", line 160, in run
    self.sync_jobs(force=True)
  File "/home/desay/.local/lib/python3.10/site-packages/gerapy/server/core/scheduler.py", line 96, in sync_jobs
    self._add_or_modify_new_jobs(task, force)
  File "/home/desay/.local/lib/python3.10/site-packages/gerapy/server/core/scheduler.py", line 152, in _add_or_modify_new_jobs
    self.scheduler.add_job(execute, task.trigger, args=[client, task.project, task.spider], id=job_id,
  File "/home/desay/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 425, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/home/desay/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 926, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/home/desay/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 904, in _create_plugin_instance
    plugin_cls = class_container[alias] = plugin_container[alias].load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'funcsigs; python_version < "3.5"' distribution was not found and is required by the application

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [乌班图 20.04 tls]
 - Browser [e.g. firefox-browser 100.0]
 - Python Version [e.g. 3.10.4]
 - Gerapy Version [e.g. 0.9.10]

**Additional context**
![2022-05-16 15-41-15 的屏幕截图](https://user-images.githubusercontent.com/40333954/168544428-b7f0dc82-c3f7-4823-9e8e-7286f5e82fc8.png)

![2022-05-16 15-40-49 的屏幕截图](https://user-images.githubusercontent.com/40333954/168544623-43657a9f-bdb7-4b05-8446-e97f76ad06ba.png)

![2022-05-16 15-40-46 的屏幕截图](https://user-images.githubusercontent.com/40333954/168544663-415c62d9-02be-4630-b86b-bc529239d9bb.png)

**Comment by InfernalAzazel** [comment]
这个bug的原因是 定时任务库 不支持 python 3.10 我的代替方案 换成 schedule 库
