### ISSUE TITLE
创建任务后无法删除，且查看任务状态加载失败，帮忙看看原因

### ISSUE THREAD

**Issue by joeycbing** [Gerapy/Gerapy#242]
ERROR - 2022-05-23 17:35:18,621 - process: 2984 - utils.py - gerapy.server.core.utils - 564 - utils - invalid literal for int() with base 10: 'zw01-teachers-job120'
Traceback (most recent call last):
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/gerapy/server/core/utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/gerapy/server/core/views.py", line 943, in task_status
    jobs = DjangoJob.objects.filter(id=job_id)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 972, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'zw01-teachers-job120'

**Comment by Germey** [comment]
与 #251 同因：旧版 `django-apscheduler` 的 `DjangoJob.id` 为整型主键，字符串 job_id 触发 `int()` 报错。当前已升级到 0.6.0（`id` 为字符串主键），该报错不再出现；job 处理也在 #326 重构。已解决。
