### ISSUE TITLE
DB error executing 'update_job' (database is locked). Retrying with a new DB connection...

### ISSUE THREAD

**Issue by clownf** [Gerapy/Gerapy#244]
**Describe the bug**
DB error executing 'update_job' (database is locked). Retrying with a new DB connection...

**To Reproduce**

**Traceback**
Traceback (most recent call last):
  File "/home/clownf/.local/lib/python3.8/site-packages/django_apscheduler/util.py", line 99, in func_wrapper
    result = func(*args, **kwargs)
  File "/home/clownf/.local/lib/python3.8/site-packages/django_apscheduler/jobstores.py", line 258, in update_job
    db_job.save()
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/models/base.py", line 780, in save_base
    updated = self._save_table(
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/models/base.py", line 853, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/models/base.py", line 903, in _do_update
    return filtered._update(values) > 0
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1471, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/clownf/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked

**Expected behavior**

**Screenshots**
<img width="942" alt="image" src="https://user-images.githubusercontent.com/23180168/171414976-1b9ef835-4f16-4b35-8ea6-fbf6641cc7f2.png">

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser [e.g. Chrome 67]
 - Python Version 3.8.10
 - Gerapy Version 0.9.10

**Additional context**

**Comment by InfernalAzazel** [comment]
兄弟我也遇到这个问题有没有解决方法？

**Comment by clownf** [comment]
> 兄弟我也遇到这个问题有没有解决方法？

暂时还没有，已准备自己写爬虫框架了

**Comment by a2011318824** [comment]
使用其它类型的数据库，不要使用默认的sqlite。我换成mysql后，就没有这个问题了

**Comment by MrDML** [comment]
> 使用其它类型的数据库，不要使用默认的sqlite。我换成mysql后，就没有这个问题了
你好，请问你如何配置的

**Comment by InfernalAzazel** [comment]
> > 使用其它类型的数据库，不要使用默认的sqlite。我换成mysql后，就没有这个问题了
> > 你好，请问你如何配置的

我早就换成 [qinglong](https://github.com/whyour/qinglong) 更先进的技术, 非常稳定又可以自动拉取 github 的爬虫项目。

**Comment by Germey** [comment]
Fixed in #324 (merged to `master`).

The SQLite connection now uses a longer busy `timeout` (`OPTIONS: {'timeout': 20}`, configurable via the `SQLITE_TIMEOUT` env var), so a blocked writer waits for the lock instead of immediately raising *database is locked* when the background scheduler thread and the web server write concurrently.

For very write-heavy deployments, enabling WAL or moving to MySQL/PostgreSQL is still recommended.
