### ISSUE TITLE
崔大，启用异步的TWISTED_REACTOR时候，部署就会报错

### ISSUE THREAD

**Issue by frshman** [Gerapy/Gerapy#247]
**Describe the bug**
启用异步的TWISTED_REACTOR时候，部署就会报错

**Traceback**
Traceback (most recent call last):
          File "D:\anaconda\envs\scrapy\lib\site-packages\twisted\web\http.py", line 2369, in allContentReceived
            req.requestReceived(command, path, version)
          File "D:\anaconda\envs\scrapy\lib\site-packages\twisted\web\http.py", line 1003, in requestReceived
            self.process()
          File "D:\anaconda\envs\scrapy\lib\site-packages\twisted\web\server.py", line 229, in process
            self.render(resrc)
          File "D:\anaconda\envs\scrapy\lib\site-packages\twisted\web\server.py", line 294, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "D:\anaconda\envs\scrapy\lib\site-packages\scrapyd\webservice.py", line 21, in render
            return JsonResource.render(self, txrequest).encode('utf-8')
          File "D:\anaconda\envs\scrapy\lib\site-packages\scrapyd\utils.py", line 21, in render
            r = resource.Resource.render(self, txrequest)
          File "D:\anaconda\envs\scrapy\lib\site-packages\twisted\web\resource.py", line 263, in render
            return m(request)
          File "D:\anaconda\envs\scrapy\lib\site-packages\scrapyd\webservice.py", line 88, in render_POST
            spiders = get_spider_list(project, version=version)
          File "D:\anaconda\envs\scrapy\lib\site-packages\scrapyd\utils.py", line 134, in get_spider_list
            raise RuntimeError(msg.encode('unicode_escape') if six.PY2 else msg)
        builtins.RuntimeError: D:\anaconda\envs\scrapy\lib\site-packages\scrapy\utils\project.py:81: ScrapyDeprecationWarning: Use of environment variables prefixed with S
CRAPY_ to override settings is deprecated. The following environment variables are currently defined: EGG_VERSION
          warnings.warn(
        Traceback (most recent call last):
          File "D:\anaconda\envs\scrapy\lib\runpy.py", line 192, in _run_module_as_main
            return _run_code(code, main_globals, None,
          File "D:\anaconda\envs\scrapy\lib\runpy.py", line 85, in _run_code
            exec(code, run_globals)
          File "D:\anaconda\envs\scrapy\lib\site-packages\scrapyd\runner.py", line 46, in <module>
            main()
          File "D:\anaconda\envs\scrapy\lib\site-packages\scrapyd\runner.py", line 43, in main
            execute()
          File "D:\anaconda\envs\scrapy\lib\site-packages\scrapy\cmdline.py", line 144, in execute
            cmd.crawler_process = CrawlerProcess(settings)
          File "D:\anaconda\envs\scrapy\lib\site-packages\scrapy\crawler.py", line 280, in __init__
            super().__init__(settings)
          File "D:\anaconda\envs\scrapy\lib\site-packages\scrapy\crawler.py", line 156, in __init__
            self._handle_twisted_reactor()
          File "D:\anaconda\envs\scrapy\lib\site-packages\scrapy\crawler.py", line 343, in _handle_twisted_reactor
            install_reactor(self.settings["TWISTED_REACTOR"], self.settings["ASYNCIO_EVENT_LOOP"])
          File "D:\anaconda\envs\scrapy\lib\site-packages\scrapy\utils\reactor.py", line 66, in install_reactor
            asyncioreactor.install(eventloop=event_loop)
          File "D:\anaconda\envs\scrapy\lib\site-packages\twisted\internet\asyncioreactor.py", line 308, in install
            reactor = AsyncioSelectorReactor(eventloop)
          File "D:\anaconda\envs\scrapy\lib\site-packages\twisted\internet\asyncioreactor.py", line 63, in __init__
            raise TypeError(
        TypeError: ProactorEventLoop is not supported, got: <ProactorEventLoop running=False closed=False debug=False>

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python Version  3.8.2
 - Gerapy Version 0.9.10

**Comment by frshman** [comment]
解决了哈，发现没有打包，如果还不行，看看有没有install_reactor

**Comment by Germey** [comment]
traceback 是 Scrapy/Twisted 在 **Windows** 上安装 asyncio reactor 的限制：`ProactorEventLoop is not supported`（scrapyd 端 get_spider_list 触发），与 Gerapy 无关。解决办法：在项目 settings 用 SelectorEventLoop（`asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())`），或在 Linux 上运行 scrapyd。按上游限制关闭。
