### ISSUE TITLE
执行gerapy migrate出现报错ImportError: cannot import name 'parse_header_parameters' from 'django.utils.http'

### ISSUE THREAD

**Issue by tsdking** [Gerapy/Gerapy#307]
**Describe the bug**
执行gerapy migrate出现报错ImportError: cannot import name 'parse_header_parameters' from 'django.utils.http'

**To Reproduce**

**Traceback**
```
Traceback (most recent call last):
  File "~/python_venv/spider/bin/gerapy", line 8, in <module>
    sys.exit(cmd())
  File "~/python_venv/spider/lib/python3.8/site-packages/gerapy/cmd/__init__.py", line 171, in cmd
    manage()
  File "~/python_venv/spider/lib/python3.8/site-packages/gerapy/server/manage.py", line 24, in manage
    execute_from_command_line(sys.argv)
  File "~/python_venv/spider/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "~/python_venv/spider/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "~/python_venv/spider/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "~/python_venv/spider/lib/python3.8/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "~/python_venv/spider/lib/python3.8/site-packages/django/core/management/base.py", line 387, in check
    all_issues = self._run_checks(
  File "~/python_venv/spider/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "~/python_venv/spider/lib/python3.8/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "~/python_venv/spider/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "~/python_venv/spider/lib/python3.8/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "~/python_venv/spider/lib/python3.8/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "~/python_venv/spider/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "~/python_venv/spider/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "~/python_venv/spider/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "~/python_venv/spider/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/python_venv/spider/lib/python3.8/site-packages/gerapy/server/server/urls.py", line 22, in <module>
    url(r'^', include('gerapy.server.core.urls')),
  File "~/python_venv/spider/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/python_venv/spider/lib/python3.8/site-packages/gerapy/server/core/urls.py", line 2, in <module>
    from rest_framework.authtoken import views as auth
  File "~/python_venv/spider/lib/python3.8/site-packages/rest_framework/authtoken/views.py", line 1, in <module>
    from rest_framework import parsers, renderers
  File "~/python_venv/spider/lib/python3.8/site-packages/rest_framework/parsers.py", line 18, in <module>
    from django.utils.http import parse_header_parameters
ImportError: cannot import name 'parse_header_parameters' from 'django.utils.http' (~/python_venv/spider/lib/python3.8/site-packages/django/utils/http.py)
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS:ubuntu 22
 - Browser bash
 - Python Version 3.8.10
 - Gerapy Version 0.9.13

**Additional context**

```
Name: Django
Version: 2.2.28
Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Home-page: https://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD
Location:~/python_venv/spider/lib/python3.8/site-packages
Requires: sqlparse, pytz
Required-by: gerapy, djangorestframework, django-cors-headers, django-apscheduler
```

```
Name: djangorestframework
Version: 3.15.2
Summary: Web APIs for Django, made easy.
Home-page: https://www.django-rest-framework.org/
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location:~/python_venv/spider/lib/python3.8/site-packages
Requires: backports.zoneinfo, django
Required-by: gerapy
```

**Comment by Germey** [comment]
已在 #327 修复并合并到 `master`。

根因：`pyproject.toml` 将 Django 锁在 `>=2.2,<3.0`，但 `djangorestframework` 没有上限。`pip install gerapy` 会装上最新 DRF（3.17.x），而 DRF 自 3.14 起不再支持 Django 2.2 并引入了 `django.utils.http.parse_header_parameters`（该函数仅 Django ≥ 4.1 提供），于是 `gerapy migrate` 抛出 ImportError。

现已将 DRF 限制为 `>=3.11.2,<3.14`（3.13.1 是最后一个支持 Django 2.2 的版本）。

本地 E2E：全新虚拟环境安装后解析到 `djangorestframework 3.13.1`，`gerapy migrate` 全部迁移成功、`gerapy runserver` 正常启动。
