### ISSUE TITLE
AttributeError: 'ManyToManyRel' object has no attribute 'field_name'

### ISSUE THREAD

**Issue by Germey** [Gerapy/Gerapy#36]
gerapy migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, core, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying core.0001_initial... OK
  Applying core.0002_auto_20180119_1210... OK
  Applying core.0003_auto_20180123_2304... OK
  Applying core.0004_auto_20180124_0032...Traceback (most recent call last):
  File "/root/anaconda3/bin/gerapy", line 11, in <module>
    load_entry_point('gerapy==0.8.5', 'console_scripts', 'gerapy')()
  File "/root/anaconda3/lib/python3.6/site-packages/gerapy-0.8.5-py3.6.egg/gerapy/cmd/__init__.py", line 26, in cmd
    server()
  File "/root/anaconda3/lib/python3.6/site-packages/gerapy-0.8.5-py3.6.egg/gerapy/cmd/server.py", line 6, in server
    manage()
  File "/root/anaconda3/lib/python3.6/site-packages/gerapy-0.8.5-py3.6.egg/gerapy/server/manage.py", line 24, in manage
    execute_from_command_line(sys.argv)
  File "/root/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/root/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/root/anaconda3/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/root/anaconda3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/root/anaconda3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/root/anaconda3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/root/anaconda3/lib/python3.6/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/root/anaconda3/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 304, in database_forwards
    to_model._meta.get_field(self.new_name),
  File "/root/anaconda3/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 81, in alter_field
    any(r.field_name == old_field.name for r in model._meta.related_objects)):
  File "/root/anaconda3/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 81, in <genexpr>
    any(r.field_name == old_field.name for r in model._meta.related_objects)):
AttributeError: 'ManyToManyRel' object has no attribute 'field_name'

**Comment by Germey** [comment]
gerapy==0.8.5
python==Python 3.6.3
Django==2.0

**Comment by Germey** [comment]
Linux version 2.6.32-431.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Fri Nov 22 03:15:09 UTC 2013
CentOS 6.5
