### ISSUE TITLE
Spider Build Failed 

### ISSUE THREAD

**Issue by mtaziz** [Gerapy/Gerapy#6]
I am having issues in `building` the spider . Let me explain, for example, how I am running the spider steps given below:

- > First off, command 
``` gerapy runserver```

- > add client 

- > copy the spider project in `gerapy/projects`

- > refresh the front end 

- > `mifarma_es_spider` being appeared on the front end 
- > click on `deploy`
- > write `description` under `Build Project`
- > click build 
- > getting `Failed to Build` and log below 

```
[01/Nov/2017 11:26:14] "POST /api/project/mifarma_es_spider/build HTTP/1.1" 500 103186
{'settings': 'mifarma_es_spider.settings', 'project': 'mifarma_es_spider'}
Built mifarma_es_spider into /home/scraper/py36projects/gerapy/projects/mifarma_es_spider/mifarma_es_spider-1.0-py3.6.egg
Internal Server Error: /api/project/mifarma_es_spider/build
Traceback (most recent call last):
  File "/home/scraper/projects/py36env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/scraper/projects/py36env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/scraper/projects/py36env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/scraper/projects/py36env/lib/python3.6/site-packages/gerapy/server/core/views.py", line 394, in project_build
    return JsonResponse(data)
  File "/home/scraper/projects/py36env/lib/python3.6/site-packages/gerapy/server/core/response.py", line 32, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/scraper/projects/py36env/lib/python3.6/site-packages/gerapy/server/core/encoder.py", line 48, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Client' is not JSON serializable
```
![Screenshot for `client`  status can be found ](https://user-images.githubusercontent.com/3662583/32259198-fe6a0b46-bee8-11e7-85da-0824a8811509.png)

I am not sure what causing this.

**Comment by Germey** [comment]
I'm really sorry for replying you since I'm occupying on my Paper these two months.  
I've tested this module in my project but I never meet this error. And during my usage of Gerapy, Build Module is well worked too.
But according to the traceback, I judge it is caused by JSON serialize error. So I add a judgement of Client Object and add `model_to_dict` transformer of it, see https://github.com/Gerapy/Gerapy/commit/2cc6eed7e72f431268a580f1c84f8a03fe6c28b9
and I've updated Gerapy to 0.7.8, hope it can solve your problem. If this doesn't work, I'll continue to   solve it, please upgrade Gerapy and test this.
Feel so sorry to reply you so late, my apologize again.

**Comment by Germey** [comment]
Version upgraded to 0.8.0~

**Comment by haxor337** [comment]
Thanks to cui qingcai's contribution to the open source framework, the framework is installed normally, and then you can expand it according to your ideas, but it can also be used in other application scenarios.

**Comment by Germey** [comment]
@haxor337 Great thanks!
