### ISSUE TITLE
新创建的项目报这个错误sqlite3.OperationalError: no such table: core_client

### ISSUE THREAD

**Issue by freedom-wy** [Gerapy/Gerapy#63]
`
(gerapy_demo) [root@localhost gerapy_project]# gerapy runserver 192.168.130.120:8000
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, core, sessions.
Run 'python manage.py migrate' to apply them.

May 31, 2018 - 23:15:33
Django version 2.0.5, using settings 'gerapy.server.server.settings'
Starting development server at http://192.168.130.120:8000/
Quit the server with CONTROL-C.
[31/May/2018 23:15:49] "GET / HTTP/1.1" 200 619
[31/May/2018 23:15:49] "GET /static/js/e7f4128e.js HTTP/1.1" 200 1406
[31/May/2018 23:15:49] "GET /static/js/314e2244.js HTTP/1.1" 200 117894
[31/May/2018 23:15:49] "GET /static/css/631f3db5.css HTTP/1.1" 200 314497
[31/May/2018 23:15:49] "GET /static/images/864753ef.svg HTTP/1.1" 200 1758
[31/May/2018 23:15:49] "GET /static/js/7bd96925.js HTTP/1.1" 200 3085651
[31/May/2018 23:15:50] "GET /api/index/status HTTP/1.1" 301 0
[31/May/2018 23:15:50] "GET /static/images/0aa9679a.png HTTP/1.1" 200 18375
[31/May/2018 23:15:50] "GET /static/fonts/af7ae505.woff2 HTTP/1.1" 200 77160
Internal Server Error: /api/index/status/
Traceback (most recent call last):
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: core_client

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/gerapy_demo/lib/python3.6/site-packages/gerapy/server/core/views.py", line 42, in index_status
    for client in clients:
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/models/query.py", line 272, in __iter__
    self._fetch_all()
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1066, in execute_sql
    cursor.execute(sql, params)
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/root/gerapy_demo/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: core_client
[31/May/2018 23:15:50] "GET /api/index/status/ HTTP/1.1" 500 126679
Not Found: /favicon.ico
[31/May/2018 23:15:50] "GET /favicon.ico HTTP/1.1" 404 8107
`

**Comment by Germey** [comment]
```
gerapy migrate
```

migrate? 执行了吗？
