### ISSUE TITLE
deploy BUG

### ISSUE THREAD

**Issue by ryan-bin** [Gerapy/Gerapy#64]
```python
[08/Jun/2018 16:31:47] "GET /api/client/1/project/scrapydemo/version HTTP/1.1" 500 111542
Internal Server Error: /addversion.json
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gerapy/server/core/middlewares.py", line 13, in __call__
    request._body = data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 303-304: invalid continuation byte
```

**Comment by wushenchao** [comment]
I have encountered the same problem, how did you solve it?

**Comment by Luoxcat** [comment]
Centos7 python3.6 had same problem
Internal Server Error: /addversion.json
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/gerapy/server/core/middlewares.py", line 13, in __call__
    request._body = data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 300-301: invalid continuation byte

**Comment by Germey** [comment]
fixed, please try the latest version.
