### ISSUE TITLE
使用定时任务调度的时候，发现爬虫运行错误

### ISSUE THREAD

**Issue by zhangjuynag96** [Gerapy/Gerapy#88]
Traceback (most recent call last):
  File "/home/zjy/workspace/gerapy-dev/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/zjy/workspace/gerapy-dev/lib/python3.7/site-packages/gerapy-0.8.6b2-py3.7.egg/gerapy/server/core/scheduler.py", line 36, in execute
    scrapyd.schedule(project_name, spider_name)
  File "/home/zjy/workspace/gerapy-dev/lib/python3.7/site-packages/scrapyd_api/wrapper.py", line 188, in schedule
    json = self.client.post(url, data=data, timeout=self.timeout)
  File "/home/zjy/workspace/gerapy-dev/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/zjy/workspace/gerapy-dev/lib/python3.7/site-packages/scrapyd_api/client.py", line 38, in request
    return self._handle_response(response)
  File "/home/zjy/workspace/gerapy-dev/lib/python3.7/site-packages/scrapyd_api/client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: Scrapy 1.5.1 - no active project

Unknown command: list

Use "scrapy" to see available commands

scrapyd中没有运行的日志

**Comment by zhangjuynag96** [comment]
![image](https://user-images.githubusercontent.com/37923854/49207656-88f10e80-f3f0-11e8-9ff7-464747f6f7fe.png)

**Comment by zhangjuynag96** [comment]
gerapy 0.8.6b2 
ubuntu 16.04
scrapy 1.5.1
scrapyd 1.2.0

**Comment by hantmac** [comment]
刚刚测试了下，这个是Django接口的问题，/api/task/(\d+)/info, 报错 `json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)`，原因是返回的json格式错误
